const ActionsType = {
  // user
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_USER_DETAIL: 'SET_USER_DETAIL',
  SET_TOKEN: 'SET_TOKEN',
  SET_USER_TYPE: 'SET_USER_TYPE',
  FEATURED_PRODUCTS: 'FEATURED_PRODUCTS',
  FEATURED_ANTIQUES: 'FEATURED_ANTIQUES',
  FEATURED_HANDMADE: 'FEATURED_HANDMADE',
  HANDMADE: 'HANDMADE',
  ANTIQUES: 'ANTIQUES',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  LOADING: 'LOADING',
  ACTIVE_PAGE: 'ACTIVE_PAGE',

  API_ERROR: 'API_ERROR',
  API_SUCCESS: 'API_SUCCESS',
}

export default ActionsType
